x = 25
y = 15
print('result x+y =', x+y)
print('result x-y =', x-y)
print('result x/y =', x/y)
print('result x*y =', x*y)
print('result x//y =', x//y)
print('result x%y =', x%y)
print('result x**y =', x**y)